# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeStarterKit' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for RNApp
    pod 'Firebase/Core', '~> 5.9.0'
    pod 'Firebase/Messaging', '~> 5.9.0'
    pod 'Fabric', '~> 1.7.11'
    pod 'Crashlytics', '~> 3.10.7'
end

